name: Staff CD Pipeline

on:
  push:
    branches:
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
              
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mimi2
          password: mimi002@@
          
      - name: Build and push Docker image for customer-management-service
        run: |
          docker build -t mimi2/customer-management-service ./staff-web-app/customer-management-service
          docker push mimi2/customer-management-service

      - name: Build and push Docker image for order-management-service
        run: |
          docker build -t mimi2/order-management-service ./staff-web-app/order-management-service
          docker push mimi2/order-management-service

      - name: Build and push Docker image for product-management-service
        run: |
          docker build -t mimi2/product-management-service ./staff-web-app/product-management-service
          docker push mimi2/product-management-service
          
      - name: Build and push Docker image for staff-authentication-service
        run: |
          docker build -t mimi2/staff-authentication-service ./staff-web-app/staff-authentication-service
          docker push mimi2/staff-authentication-service
          
     
